# Generated by Django 4.2.3 on 2023-08-02 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('anime_id', models.IntegerField()),
                ('content', models.TextField()),
                ('recommendation', models.CharField(choices=[('RE', 'Recommended'), ('MF', 'Mixed Feelings'), ('NR', 'Not Recommended')], max_length=2)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
