# Generated by Django 4.2.3 on 2023-08-13 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_recommendation_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
